Explicitly define 'view_name' and 'queryset' attrs
 - serializers.HyperlinkedIdentityField and serializers.HyperlinkedRelatedField now require 'view_name' and 'queryset' to be explicitly defined as kwargs
 - For these instances, we explicitly define the correct 'view_name' and 'queryset' params as attributes, which are then passed as kwargs to the appropriate rest_framework.serializers field.
 - We are now getting an error when calling `pagination.NextPageField(source='*')` on the rest_framework.pagination module: `AttributeError: 'module' object has no attribute 'NextPageField'`